language: python
cache: pip
sudo: required
dist: xenial
python:
  - "3.7"

addons:
  apt:
    sources:
     #- sourceline: 'deb [trusted=yes] https://debian.unknown-horizons.org/travis/ /'
     - sourceline: 'deb [trusted=yes] http://ftp.debian.org/debian/ unstable main non-free contrib'

before_install:
  - "sudo apt-get update"
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3 # give xvfb some time to start

install:
  - sudo apt-get install python3-fife python3-enet libfifechan0.1.5
  - sudo apt-get install intltool
  # libfifechan0.1.5 is version 0.1.5 on the repo
  # python3-fife is version 0.4.2 on the repo
  - pip3 install -r requirements.txt

script:
  - "cp -a /usr/lib/python3/dist-packages/fife/ $VIRTUAL_ENV/lib/python3.7/site-packages/"
  - "cp -a /usr/lib/python3/dist-packages/enet* $VIRTUAL_ENV/lib/python3.7/site-packages/"
  #- "prename 's/\\.cpython-37m-x86_64-linux-gnu/.cpython-37m/' $VIRTUAL_ENV/lib/python3.7/site-packages/enet*.so"
  #- "prename 's/\\.cpython-36m-x86_64-linux-gnu/.cpython-36m/' $VIRTUAL_ENV/lib/python3.6/site-packages/fife/*.so"
  - mv $VIRTUAL_ENV/lib/python3.7/site-packages/fife/_fife.cpython-3*m-x86_64-linux-gnu.so $VIRTUAL_ENV/lib/python3.7/site-packages/fife/_fife.so
  - mv $VIRTUAL_ENV/lib/python3.7/site-packages/fife/_fifechan.cpython-3*m-x86_64-linux-gnu.so $VIRTUAL_ENV/lib/python3.7/site-packages/fife/_fifechan.so
  - python3 -c 'from fife import fife; print(fife.getVersion())'
  - isort -c -rc horizons tests *.py
  - pycodestyle horizons tests *.py development
  - ./setup.py build_i18n
  - COVERAGE_FILE=.coverage.nongui pytest --verbose --cov --cov-report= -rs
  - RUNCOV=1 pytest --gui-tests tests/gui --verbose --cov --cov-report= -rs

after_success:
  - coverage combine
  - coveralls

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#unknown-horizons"
    skip_join: false
    use_notice: false
